### PR TITLE
REFUSALOFINSTALL.md

### PR DESCRIPTION
**Pull request by VenomousSteam81**
This file instructs on how to install PojavLauncher if you get the message below
Image

### CODE REVIEW

**Review by mchnjt — CHANGES_REQUESTED** [review]
I would've merged this PR by now, but uhh
- You've made an entire new page. This won't be directly displayed unless it's added in the config file (`.vuepress/config.js`)

Consider adding it on the config file. After you did so, please notify me and I'll look into it if you added it correctly.

**Comment by VenomousSteam81** [comment]
Alright, I'll fix when I get to school.

**Comment by VenomousSteam81** [comment]
Alright, Its done @phyr1sc

**Review by mchnjt — APPROVED** [review]

**Comment by mchnjt** [comment]
LGTM, thank you for contributing for the wiki

**Pull request merged**
