### PR TITLE
Update MODS-UNSUPPORTED.md

### PR DESCRIPTION
**Pull request by Fl414r**
Remove duplicate and add another unsupported mod

### CODE REVIEW

**Comment by Fl414r** [comment]
By the way, why Essential and Skyblock mods still here?
I checked my small Skyblock modpack right now, some mod breaks fonts and entities, but if you forget about this little thing, everything works perfectly.

**Comment by Fl414r** [comment]
Patcher (v1.8.7) broke fonts and entities. After I removed it everything was fixed.
But how much it lags, after the perfectly optimized 1.19 and 1.20 it's hard to play...
Of course, I didn’t set up the mods, maybe even the patcher can be fixed by disabling the unnecessary option, but even taking into account the calculation of the usual settings for the PC, it lags too much.

**Review by GodForbidMePwese — COMMENTED** [review]
Incomplete

**Comment by mchnjt** [comment]
Will be checking on this.

**Comment by mchnjt** [comment]
@Fl414r You claimed in this PR that the Essential mod works. Can you upload any proof or workaround that you applied?

**Comment by GaucovyAero** [comment]
Essential sometimes works and sometimes doesn't. We can't really do anything about it other than leave it unsupported. Last time, they implemented a feature that was scanning your CPU (tracking, telemetry) and since pojav reports it as "null", it was crashing. Then they maybe got some issues about it and fixed the issue. We are not in contact with any Essential devs, and they specifically state on their website/discord server/whatever that Pojav is not supported. Since it's proprietary, we also can't support it.

**Pull request closed without merging**
