### PR TITLE
Update config.js

### PR DESCRIPTION
**Pull request by ItAnthon**
Removed “Dealing With iOS Memory Limits” from .vuepress/config.js

Eva deemed out of date and no longer needed

### CODE REVIEW

**Review by GaucovyAero — APPROVED** [review]
good

**Comment by GaucovyAero** [comment]
you have kinda uh deleted the file from the wrong branch inb4, i mean i merged it but its not inside main, so be sure to redo it in this pull request

**Comment by ItAnthon** [comment]
> you have kinda uh deleted the file from the wrong branch inb4, i mean i merged it but its not inside main, so be sure to redo it in this pull request

Wait redo what specifically im kinda lost lol

**Comment by ItAnthon** [comment]
I think i got everything for here actually

**Comment by GaucovyAero** [comment]
yeah uh the compatability thing again, but almost perfect

**Review by GaucovyAero — APPROVED** [review]
approved

**Pull request merged**
