### PR TITLE
Updated Unsupported Mods List, and Optimization

### PR DESCRIPTION
**Pull request by ZenZenXDz**
Big black burly men coming in to my house at 3 am

### CODE REVIEW

**Review by mchnjt — APPROVED** [review]
Asking @Aerolome for review as this is regarding to unsupported mods.

**Review by GaucovyAero — DISMISSED** [review]
epikus, but review dis file and merge it into your fork if you can epik
[MODS-UNSUPPORTED.md](https://github.com/PojavLauncherTeam/pojavlauncherteam.github.io/files/9944072/MODS-UNSUPPORTED.md)

**Comment by ZenZenXDz** [comment]
I merged it 😩

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by ZenZenXDz — COMMENTED** [review]
Meow

**Comment by mchnjt** [comment]
Mayhaps we can call this a... stale PR...? Don't worry though, well merge your work with #15 so that we don't waste your hard work. Thanks for making the PojavLauncher wiki better!

**Pull request closed without merging**
