### PR TITLE
Update INSTALL.md

### PR DESCRIPTION
**Pull request by ItAnthon**
Updated TrollStore Compatability list

### CODE REVIEW

**Comment by GaucovyAero** [comment]
you have a typo, edit Trollstore to TrollStore

**Comment by ItAnthon** [comment]
I untypoed it

**Comment by GaucovyAero** [comment]
oops, also, its TrollStore compatibility and not compatability :D

**Comment by ItAnthon** [comment]
> oops, also, its TrollStore compatibility and not compatability :D

2nd language moment mb 

ill fix, plus this was to the wrong thing also lol

ill close this and make a new one (same changes)

**Pull request closed without merging**
